run:
  timeout: 5m
  tests: true
  skip-dirs:
    - "vendor"
    - "mocks"
    - "third_party"
  linters:
    enable-all: false
    enable:
      - govet
      - errcheck
      - staticcheck
      - gosimple
      - unused
      - deadcode
      - structcheck
      - varcheck
      - ineffassign
      - typecheck
      - gofmt
      - goimports
      - golint
      - depguard
      - dupl
      - gocyclo
      - misspell
      - unconvert
      - unparam
      - whitespace
      - prealloc
      - scopelint
      - stylecheck
      - dogsled
    disable:
      - godot
      - gochecknoglobals
      - gochecknoinits
      - funlen  # Disable function length linter if not needed
  modules-download-mode: readonly

linters-settings:
  golint:
    min-confidence: 0.8
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  misspell:
    locale: US
  depguard:
    list-type: blacklist
    packages:
      - "log"
    packages-with-error-message:
      "log": "Use 'github.com/sirupsen/logrus' instead of the standard 'log' package"
  prealloc:
    simple: true

issues:
  exclude-use-default: false
  exclude-rules:
    - path: "_test\\.go"
      linters:
        - golint
        - gofmt
    - linters:
        - errcheck
      text: ".*Close.*"
    - linters:
        - staticcheck
      text: "SA1019"  # Ignore deprecation warnings if necessary

exclude:
  - "vendor/"
  - "third_party/"
  - "mocks/"

output:
  format: tab  # Or "colored-line-number" for colorized output
